export const APPLICATION_BASE_ROUTE = "/application";

export const pageName = {
  LOGIN: "login",
  REGISTRATION: "registration",
  FORGOT_PASSWORD: "forgotPassword",
  RESET_PASSWORD: "resetpassword",
  BORROWER_PORTAL: "borrower",
  APPLY_BORROWER: "apply-borrower",
  APPLY_CONTRACTOR: "apply-contractor",
  PRIVACY_POLICY: "privacy-policy",
  PRIVACY_NOTE: "privacy-note",
  ECONSENT: "econsent",
  TERMS_AND_CONDITIONS: "terms-and-conditions",
  KUKUN: "kukun",
};

const {
  LOGIN,
  FORGOT_PASSWORD,
  RESET_PASSWORD,
  BORROWER_PORTAL,
  APPLY_BORROWER,
  APPLY_CONTRACTOR,
  REGISTRATION,
  PRIVACY_POLICY,
  PRIVACY_NOTE,
  ECONSENT,
  TERMS_AND_CONDITIONS,
  KUKUN,
} = pageName;

export const routes = {
  HOME: `${APPLICATION_BASE_ROUTE}/`,
  LOGIN: `${APPLICATION_BASE_ROUTE}/${LOGIN}`,
  REGISTRATION: `${APPLICATION_BASE_ROUTE}/${REGISTRATION}`,
  FORGOT_PASSWORD: `${APPLICATION_BASE_ROUTE}/${LOGIN}/${FORGOT_PASSWORD}`,
  RESET_PASSWORD: `${APPLICATION_BASE_ROUTE}/${RESET_PASSWORD}`,
  BORROWER_PORTAL: `${APPLICATION_BASE_ROUTE}/${BORROWER_PORTAL}/`,
  APPLY_BORROWER: `${APPLICATION_BASE_ROUTE}/${APPLY_BORROWER}/`,
  APPLY_BORROWER_AUTHORIZED: `${APPLICATION_BASE_ROUTE}/${APPLY_BORROWER}/:id`,
  APPLY_CONTRACTOR: `${APPLICATION_BASE_ROUTE}/${APPLY_CONTRACTOR}/`,
  APPLY_CONTRACTOR_AUTHORIZED: `${APPLICATION_BASE_ROUTE}/${APPLY_CONTRACTOR}/:id`,
  PRIVACY_POLICY: `${APPLICATION_BASE_ROUTE}/policies/${PRIVACY_POLICY}`,
  PRIVACY_NOTE: `${APPLICATION_BASE_ROUTE}/policies/${PRIVACY_NOTE}`,
  ECONSENT: `${APPLICATION_BASE_ROUTE}/policies/${ECONSENT}`,
  TERMS_AND_CONDITIONS: `${APPLICATION_BASE_ROUTE}/policies/${TERMS_AND_CONDITIONS}`,
  KUKUN: `${APPLICATION_BASE_ROUTE}/${KUKUN}`,
};
