export default () => ({
  bankruptcyTypes: [
    'CB',
    'TB',
    '1D',
    '1F',
    '1V',
    '1X',
    '2D',
    '2F',
    '2V',
    '2X',
    '3D',
    '3F',
    '3V',
    '3X',
    '7D',
    '7F',
    '7V',
    '7X',
  ],
  foreclosureTypes: ['DF', 'FC', 'SF'],
  productId: '5d31fdaca346c509f4fd3c14',
  minCreditScore: 0,
  maxCreditScore: 900,
  newPartnerRuleSet: {
    isDeleted: false,
    version: 1,
    rules: {
      rule0: {
        ruleId: 's2_bu_0',
        description: 'No-hit',
        declinedIf: 'eq',
        value: true,
        disabled: false,
        weight: 5,
      },
      rule1: {
        ruleId: 's2_bu_1',
        description: 'Months of Credit History',
        declinedIf: 'lt',
        value: 12,
        disabled: false,
        weight: 1,
      },
      rule2: {
        ruleId: 's2_bu_2',
        description: 'Active Trade Lines',
        declinedIf: 'lt',
        value: 1,
        disabled: false,
        weight: 1,
      },
      rule3: {
        ruleId: 's2_bu_3',
        description: 'Revolving Trade Lines',
        declinedIf: 'lt',
        value: 1,
        disabled: false,
        weight: 1,
      },
      rule4: {
        ruleId: 's2_bu_4',
        description: 'Inquiries in the last 6 Months',
        declinedIf: 'gt',
        value: 12,
        disabled: false,
        weight: 1,
      },
      rule5: {
        ruleId: 's2_bu_5',
        description: 'Bankruptcies in the Last 24 Months',
        declinedIf: 'gt',
        value: 0,
        disabled: false,
        weight: 3,
      },
      rule6: {
        ruleId: 's2_bu_6',
        description: 'Foreclosures in the Last 24 Months',
        declinedIf: 'gt',
        value: 0,
        disabled: false,
        weight: 2,
      },
      rule7: {
        ruleId: 's2_bu_7',
        description: 'Public Records in the Last 24 Months',
        declinedIf: 'gt',
        value: 5,
        disabled: false,
        weight: 1,
      },
      rule8: {
        ruleId: 's2_bu_8',
        description: 'Trades with 60+ DPD in the Last 24 Months',
        declinedIf: 'gt',
        value: 4,
        disabled: false,
        weight: 2,
      },
      rule9: {
        ruleId: 's2_bu_9',
        description: 'Trades with 60+ DPD in the Last 6 Months',
        declinedIf: 'gt',
        value: 2,
        disabled: false,
        weight: 1,
      },
      rule10: {
        ruleId: 's2_bu_10',
        description: 'Utilization of Revolving Trades',
        declinedIf: 'gt',
        value: 0.9,
        disabled: false,
        weight: 1,
      },
    },
  },
});
